{
 "title": "General Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rate  by action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(myapp_http_requests_total{action!~\"all\"}[$__rate_interval])) by (action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action!~\"all\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action!~\"all\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action!~\"all\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1, sum by(le,action) (rate(myapp_request_durations_histogram_seconds_bucket{action!~\"all\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (4**|5**)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((sum(rate(myapp_http_5xx_responses_total[5m] )) by (action) or sum(rate(myapp_http_4xx_responses_total[5m])) by (action))/ sum(rate(myapp_request_durations_histogram_seconds_count[5m])) by (action) )*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}