apiVersion: v1
kind: Service
metadata:
  name: {{ include "profile.fullname" . }}
  labels:
    {{- include "profile.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "profile.selectorLabels" . | nindent 4 }}