apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-profile-config
  labels:
    app: postgresql
data:
  POSTGRES_DB: app_db_profile
  DB_HOST: {{ .Values.postgresql.fullnameOverride }}
  DB_PORT: "5432"
