apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: postgresql
data:
  POSTGRES_DB: database_app_shared
  DB_HOST: {{ .Values.postgresql.fullnameOverride }}
  DB_PORT: "5432"
