apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=     # printf postgres | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # printf password | base64
  USER: dXNlcg==     # printf user | base64
  PASSWORD: cGFzc3dvcmQ= # printf password | base64