apiVersion: v1
kind: Service
metadata:
  name: {{ include "app_chart.fullname" . }}
  labels:
    {{- include "app_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - protocol: {{ .Values.auth.service.protocol }}
      name: {{ .Values.auth.service.name }}
      port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
  selector:
    {{- include "app_chart.selectorLabels" . | nindent 4 }}
