apiVersion: v1
kind: Service
metadata:
  name: {{ include "app_chart.fullname" . }}-profile
  labels:
    app: myapp-profile
spec:
  type: {{ .Values.profile.service.type }}
  ports:
    - protocol: {{ .Values.profile.service.protocol }}
      name: {{ .Values.profile.service.name }}
      port: {{ .Values.profile.service.port }}
      targetPort: {{ .Values.profile.service.targetPort }}
  selector:
    app: myapp-profile
