apiVersion: v1
kind: Service
metadata:
  name: {{ include "app_chart.fullname" . }}
  labels:
    {{- include "app_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "app_chart.selectorLabels" . | nindent 4 }}
