apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/www/app #путь на виртуальной машине миникуба
  storageClassName: standard
